title: Jam Risser
name: Jam Risser
email: jam@jamrizzi.com
description: Software Engineer from Austin, TX
baseurl: ""
url: ""
twitter_username: jamrizzi
github_username:  jamrizzi
github_fork_banner: https://github.com/jamrizzi/jekyll-nerd-portfolio
skills:
  - icon: amazonwebservices-plain
    href: https://aws.amazon.com
    title: Amazon Web Services
  - icon: ruby-plain-wordmark
    href: https://www.ruby-lang.org
    title: Ruby
  - icon: python-plain-wordmark
    href: https://python.com
    title: Python
  - icon: go-plain
    href: https://golang.org
    title: Golang
  - icon: cplusplus-plain-wordmark
    href: http://www.cplusplus.com
    title: C++
  - icon: javascript-plain
    href: https://www.ecma-international.org/publications/standards/Ecma-262.htm
    title: JavaScript
  - icon: php-plain
    href: https://php.net
    title: PHP
  - icon: sass-plain
    href: http://sass-lang.com
    title: Sass
  - icon: nodejs-plain
    href: https://nodejs.org
    title: NodeJS
  - icon: linux-plain
    href: https://kernel.org
    title: Linux
  - icon: docker-plain-wordmark
    href: https://www.docker.com
    title: Docker
  - icon: nginx-plain-wordmark
    href: https://nginx.org
    title: Nginx
  - icon: django-plain-wordmark
    href: https://www.djangoproject.com
    title: Django
  - icon: mongodb-plain-wordmark
    href: https://www.mongodb.com
    title: MongoDB
  - icon: mysql-plain-wordmark
    href: https://www.mysql.com
    title: MySQL
  - icon: react-plain-wordmark
    href: https://github.com/facebook/react
    title: React
  - icon: angularjs-plain
    href: https://angular.io
    title: Angular
  - icon: bootstrap-plain-wordmark
    href: https://getbootstrap.com
    title: Bootstrap
  - icon: gulp-plain
    href: https://gulpjs.com/
    title: Gulp
  - icon: git-plain-wordmark
    href: https://git-scm.com
    title: Git
  - icon: vim-plain
    href: http://www.vim.org
    title: Vim
jekyll_analytics:
  Matomo:
    url: analytics.jamrizzi.com
    siteId: '1'
isso-url: https://comments.jamrizzi.com
comments: false
markdown: kramdown
theme: jekyll-nerd-portfolio
plugins:
  - jekyll-feed
  - jekyll-analytics
