title: Jam Risser
name: Jam Risser
email: jam@jamrizzi.com
description: Software Engineer from Austin, TX
baseurl: ""
url: ""
twitter_username: jamrizzi
github_username:  jamrizzi
skills:
  amazonwebservices: https://aws.amazon.com
  react: https://github.com/facebook/react
  ruby: https://www.ruby-lang.org
  nodejs: https://nodejs.org
  python: https://python.com
  linux: https://kernel.org
  docker: https://www.docker.com
  nginx: https://nginx.org
  go: https://golang.org
  django: https://www.djangoproject.com
  cplusplus: http://www.cplusplus.com
  bootstrap: https://getbootstrap.com
  gulp: https://gulpjs.com/
  webpack: https://webpack.js.org
  angularjs: https://angular.io
  babel: https://babeljs.io
  express: http://expressjs.com
  git: https://git-scm.com
  html5: https://www.w3.org/TR/html52
  javascript: https://www.ecma-international.org/publications/standards/Ecma-262.htm
  mongodb: https://www.mongodb.com
  mysql: https://www.mysql.com
  php: https://php.net
  sass: http://sass-lang.com
  vim: http://www.vim.org
  mocha: https://mochajs.org
markdown: kramdown
theme: jekyll-nerd-portfolio
plugins:
  - jekyll-feed
